spring.application.name=distributed-chat-system

# Database Connection
spring.datasource.url=jdbc:mysql://localhost:3306/distributedchatsystem
spring.datasource.username=root
spring.datasource.password=akshit2941

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# Connection Pool (Hikari - default)
spring.datasource.hikari.maximum-pool-size=10

jwt.secret=Xv/r39KvtLq;J8<u.%4K,o$P/{SNnRqLudpa&KUy.RY
jwt.expiration=86400000